#pragma config(Sensor, port4,  bBack,          sensorVexIQ_Touch)
#pragma config(Sensor, port5,  bLeft,          sensorVexIQ_Touch)
#pragma config(Sensor, port6,  bRight,         sensorVexIQ_Touch)
#pragma config(Sensor, port7,  LED1,           sensorVexIQ_LED)
#pragma config(Sensor, port8,  LED4,           sensorVexIQ_LED)
#pragma config(Sensor, port9,  gyro,           sensorVexIQ_Gyro)
#pragma config(Sensor, port10, LED3,           sensorVexIQ_LED)
#pragma config(Sensor, port11, LED2,           sensorVexIQ_LED)
#pragma config(Sensor, port12, LED5,           sensorVexIQ_LED)
#pragma config(Motor,  motor1,          mFront,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor2,          mLeft,         tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor3,          mRight,        tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*

Robot Name: Kennilworth Ken Kennington The 13th
Group: Braden, Jess, Paula, Emma

*/

//---------------------------------------------------------------------------------------------------------------------------------------------------//
//sine function for front motor speed
int sineFront(int x, int spd) {
	int y = spd * sinDegrees(x);
	return y;
}

//---------------------------------------------------------------------------------------------------------------------------------------------------//
//sine function for left motor speed
int sineLeft(int x, int spd) {
	int y = -spd * sinDegrees(x + 60);
	return y;
}

//---------------------------------------------------------------------------------------------------------------------------------------------------//
//sine function for right motor speed
int sineRight(int x, int spd) {
	int y = -spd * sinDegrees(x - 60);
	return y;
}

//---------------------------------------------------------------------------------------------------------------------------------------------------//
//determines the direction to travel and assigns motor speeds
void motorMath(float dir = 0, long spd) {

	setMotorSpeed(mFront, sineFront(dir, spd));
	setMotorSpeed(mLeft, sineLeft(dir, spd));
	setMotorSpeed(mRight, sineRight(dir, spd));

}

//---------------------------------------------------------------------------------------------------------------------------------------------------//
//rainbow LED function (Created By: Eric Morse)
task rainbowLED() {
	int values[5];

	for(int i; i < 5; i++) {
		values[i] = 1 + i * 51;
	}

	while(true){
		setTouchLEDHue(LED1, values[0]);
		setTouchLEDHue(LED2, values[1]);
		setTouchLEDHue(LED3, values[2]);
		setTouchLEDHue(LED4, values[3]);
		setTouchLEDHue(LED5, values[4]);
		sleep(1);
		for (int j = 0; j < 5; j++){
			values[j] += 1;
			if (values[j] > 255) {
				values[j] = 1;
			}
		}

	}

}

//---------------------------------------------------------------------------------------------------------------------------------------------------//
//speed control task
int speed = 50;

task speedControl() {
	while (true) {
		if (getJoystickValue(BtnFUp) && speed < 100) {
			speed += 10;
			displayTextLine(4, "Speed: ", speed);
			wait10Msec(10);
		} else if (getJoystickValue(BtnFDown) && speed > 0) {
			speed -= 10;
			displayTextLine(4, "speed: ", speed);
			wait10Msec(10);
		}
	}
}

//---------------------------------------------------------------------------------------------------------------------------------------------------//
//soh cah toa
void getDirection(float y, float x, int spd) {
	if (x == 0 && y == 0) {

		setMotorSpeed(mFront, 0);
		setMotorSpeed(mLeft, 0);
		setMotorSpeed(mRight, 0);

		} else if (x == 0 && y != 0) {

		if (y > 0) {
			motorMath(0-getGyroDegrees(gyro), spd);
			} else {
			motorMath(180-getGyroDegrees(gyro), spd);
		}

		} else if (x != 0 && y == 0) {

		if (x > 0) {
			motorMath(90-getGyroDegrees(gyro), spd);
			} else {
			motorMath(270-getGyroDegrees(gyro), spd);
		}

		} else {

		motorMath(radiansToDegrees(atan2(x, y))-getGyroDegrees(gyro), spd);

	}
}

//---------------------------------------------------------------------------------------------------------------------------------------------------//
//turning function
void turn(int x, int spd) {
	if (x > 0) {
		setMotorSpeed(mFront, spd);
		setMotorSpeed(mRight, spd);
		setMotorSpeed(mLeft, spd);
		} else if (x < 0) {
		setMotorSpeed(mFront, -spd);
		setMotorSpeed(mRight, -spd);
		setMotorSpeed(mLeft, -spd);
	}
	resetGyro(gyro);
}

//---------------------------------------------------------------------------------------------------------------------------------------------------//
//main function
task main()
{
	startTask(speedControl);
	startTask(rainbowLED);
	resetGyro(gyro);
	while(true) {
		if (getJoystickValue(ChC) != 0) {
			turn(getJoystickValue(ChC), speed);
		} else {
			getDirection(-getJoystickValue(ChA), getJoystickValue(ChB), speed);
		}
	}
}
